### ISSUE TITLE
Error after adding login form

### ISSUE THREAD

**Issue by olleharstedt** [bwaidelich/Wwwision.Neos.FrontendLogin#5]
Exception while rendering
page<TYPO3.Neos:Page>/
body<TYPO3.TypoScript:Template>/
content/
main<TYPO3.Neos:PrimaryContent>/
default<TYPO3.TypoScript:Matcher>/
renderer<TYPO3.Neos:ContentCollection>/
itemRenderer<TYPO3.Neos:ContentCase>/
default<TYPO3.TypoScript:Matcher>/
element<Wwwision.Neos.FrontendLogin:LoginForm>:
Invalid resource URI "resource://Wwwision.Neos.FrontendLogin/Private/Templates/NodeTypes/LoginForm.html": Package "Wwwision.Neos.FrontendLogin" is not available. (20150126152815651683)

**Comment by bwaidelich** [comment]
Was that a bug report? ;)
The exception states that the "Wwwision.Neos.FrontendLogin" has not been installed properly..
Make sure to flush caches and run the test in Development context.

**Comment by olleharstedt** [comment]
Haha, the problem was that git add `-master` at end of dir when unpacking. Solved. Sorry for your trouble.

**Comment by bwaidelich** [comment]
Thanks for the update and no worries ;)
