### ISSUE TITLE
Expand exampel to include user groups

### ISSUE THREAD

**Issue by olleharstedt** [bwaidelich/Wwwision.Neos.FrontendLogin#6]
Hi again!

How could you expand on this package to include user groups? Any ideas or hints?

Another thing, what's the current status of front-end users in Neos? Is it safe to use, with cache and such? Will there be an official package for front-end users any time soon?

Regards
Olle

**Comment by bwaidelich** [comment]
Hi Olle,
no offense but please use the TYPO3 Mailing Lists (http://typo3.org/support/mailing-lists/) for such questions so others have the chance to comment & learn from it. In this case http://forum.typo3.org/index.php/f/121/ would be the place to go.

HTH

**Comment by bwaidelich** [comment]
Re the first part of the question: This package serves as very simple first prototype and doesn't cater for groups. I'll adjust the package description to point that out.
