### ISSUE TITLE
Might be able to sponsor

### ISSUE THREAD

**Issue by olleharstedt** [bwaidelich/Wwwision.Neos.FrontendLogin#7]
Hi again again! :)

(Isn't there any other way to send messages on github??)

Our company might be able to sponsor work for front-end users etc. I sent a mail to you last week, but you never responded. Maybe wrong address? Anyway, you could contact the boss here. We would be so happy!

https://www.bitmotion.de/de/typo3-agentur.html

Regards
Olle

**Comment by bwaidelich** [comment]
Hi Olle,

what a funny way to communicate ;)
your email got filtered for some reason.. I found it in my spam folder and reply now
